# Learning Variables

- name: Learning varibles in yaml
  hosts: localhost
  tasks:
  - name: check variables
    vars: #varibles under task level
      Course: "Ansible varibles"
    ansible.builtin.debug:
      msg: "Hi {{PERSON}}, WISHING {{WISH}} "


      # WE WILL PROVIDE VARIABLE INPUT THROUGH THE COMMAND LINE